volumes:
  grafana_data:
  prometheus_data:


services:

  prometheus:
    image: bitnami/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/hosts:/etc/hosts
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - /etc/hosts:/etc/hosts
    ports:
      - "3000:3000"
